### PR TITLE
Update National Day Giveaway

### PR DESCRIPTION
**Pull request by ninjiahui**
…al Day Giveaway.md","userId":"3006"}

### CODE REVIEW

**Comment by ninjiahui** [comment]
Updated the foreigner annual subscription fee and one-time registration fee.

**Comment by ninjiahui** [comment]
Update GST for foreigner membership

**Comment by ninjiahui** [comment]
Update National Day Giveaway NRIC to XXXXXXXXX

**Comment by ninjiahui** [comment]
update giveaway to masked ID

**Review by nlslks — APPROVED** [review]
Changes approved.

**Comment by nlslks** [comment]
Merged done.

**Pull request merged**
